name: AutoApproveSimpleChanges
# Will faciliate auto approval of PR's given certain criteria are met.
# 1. Trust. Cannot be a PR from a fork. Can only be from another branch in this repo.

on: [pull_request]

jobs:
  autoapprove:
    if: ${{ !github.event.pull_request.head.repo.fork }}

    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    steps:
    - uses: actions/checkout@v3.3.0
      with:
        fetch-depth: 0
    
    - name: Git Diff Output
      run: git diff --stat
    
    - name: Output git diff from main to the latest release
      run: git diff --stat
      
