name: AutoApproveSimpleChanges
# Will faciliate auto approval of PR's given certain criteria are met.
# 1. Trust. Cannot be a PR from a fork. Can only be from another branch in this repo.
# 2. Content. Only markdown files can be changed.
# 3. Trust. PR Creator must have ______

on: [pull_request]

jobs:
  autoapprove:
    if: ${{ !github.event.pull_request.head.repo.fork }}

    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    steps:
    - uses: actions/checkout@v3.3.0
      with:
        fetch-depth: 0
    
    - name: GitHub param debug
      run: |
        echo event ${{ github.event_name }}
        echo headref ${{ github.head_ref }} 
        echo ref ${{ github.ref_name }}
        echo baseref ${{ github.base_ref }}
        
    - name: Git List remotes
      run: git remote -v
        
    - name: Git Diff Output
      run: git diff @{u} --stat
      
    - name: Output git status 
      run: git status
      
    - name: Approve PR
      env:
        GH_TOKEN: ${{ github.token }}
        PR_URL: ${{ github.event.pull_request.html_url }}
      run: |
        gh pr review --approve
