name: AutoApproveSimpleChanges
# Will faciliate auto approval of PR's given certain criteria are met.
# 1. Trust. Cannot be a PR from a fork. Can only be from another branch in this repo.
# 2. Content. Only markdown files can be changed.
# 3. Trust. PR Creator must have ______

on: [pull_request]

jobs:
  autoapprove:
    if: ${{ !github.event.pull_request.head.repo.fork }}

    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    steps:
    - uses: actions/checkout@v3.3.0
      with:
        fetch-depth: 0
        ref: ${{ github.head_ref }}
        
    - name: GitHub param debug
      run: |
        echo event ${{ github.event_name }}
        echo headref ${{ github.head_ref }} 
        echo ref ${{ github.ref_name }}
        echo baseref ${{ github.base_ref }}
        echo repoOwner ${{ github.event.repository.owner }}
        echo repoName ${{ github.event.repository.name }}
        
    - name: GitHub context inspect debug
      continue-on-error: true
      env:
        GITHUB_CONTEXT: ${{ toJson(github.event.pull_request) }}
      run: echo "$GITHUB_CONTEXT"
        
    - name: Git List remotes
      run: git remote -v
  
    - name: Output git status 
      run: git status
    
    - name: Git Diff Output 1
      run: git diff HEAD --stat
      
    - name: Git Diff Output 2
      run: git diff @{u} --stat
      
    - name: Git Diff Output baseref
      run: git diff  origin/${{ github.base_ref }} --stat

    - name: Evaluate Auto Approval
      id: evalCriteria
      run: |
        CRITERIAMET=true
        echo "CRITERIAMET=$CRITERIAMET" >> $GITHUB_OUTPUT

    - name: Dismiss approvals
      if: ${{ steps.evalCriteria.CRITERIAMET != 'true' }}
      env:
        GH_TOKEN: ${{ github.token }}
      run: |
        echo ${{ steps.evalCriteria.CRITERIAMET }}
        echo ${{ steps.evalCriteria.CRITERIAMET != 'true' }}

        gh api repos/${{ github.event.repository.owner }}/pulls/${{ github.event.repository.name }}/reviews --jq '.[] | [.id,.state] | join("=")' | grep -Po '\d+(?=\=APPROVED)' | xargs -I '@(review_id)' gh api repos/${{ github.event.repo.name }}/pulls/${{ github.event.number }}/reviews/@(review_id)/dismissals

    - name: Approve PR
      if: ${{ steps.evalCriteria.CRITERIAMET == 'true' }}
      env:
        GH_TOKEN: ${{ github.token }}
        PR_URL: ${{ github.event.pull_request.html_url }}
      run: gh pr review --approve
