# Checks for broken links

name: Broken Link Checker

on:
  schedule:
    - cron: 0 0 1 * * # run monthly

  workflow_dispatch:

jobs:
  check:
    name: Broken Link Check
    runs-on: ubuntu-latest
    steps:
      - name: Repo - Broken Link Check
        uses: technote-space/broken-link-checker-action@v2
        with: 
          TARGET: https://github.com/Azure/AKS-Construction/blob/main/README.md
        
      - name: Helper - Broken Link Check
        uses: technote-space/broken-link-checker-action@v2
        with: 
          TARGET: https://azure.github.io/AKS-Construction/
          RECURSIVE: false
      - name: Helper (preview) - Broken Link Check
        uses: technote-space/broken-link-checker-action@v2
        with: 
          TARGET: https://azure.github.io/AKS-Construction/?feature=defender
          RECURSIVE: false
