# This is a basic workflow to help you get started with Actions

name: BuildAzureVoteAppForACR

on:
 workflow_dispatch:
   inputs:
      acrName:
        description: 'Azure Container Registry Name'
        type: text
        required: true
      doDebugSteps:
        description: 'Run informational steps'
        default: 'true'
        type: boolean
        required: false
 
 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Azure Login
        uses: Azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: ACR build
        id: acr
        uses: gordonby/acr-build@main
        with:
          registry: github.event.inputs.acrName
          repository: Azure-Samples/azure-voting-app-redis
          image: azurevote
          folder: azure-vote
