name: Environment Variable Workflow

on:
  workflow_dispatch:

jobs:
  greet:
    runs-on: ubuntu-latest
    environment: gordonsEnv1

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell
    - name: Echo environment variable value
      run: echo "Hello ${{ VARS.ENABLETELEMETRY }}"
    - name: Echo environment variable condition
      run: echo "Hello ${{ VARS.ENABLETELEMETRY == true }}"
    - name: Echo environment variable condition with quotes
      run: echo "Hello ${{ VARS.ENABLETELEMETRY == 'true' }}"
    - name: Echo non existant environment variable condition with quotes
      run: echo "Hello ${{ VARS.SPAGHETTI == 'true' }}"
