
name: Resuable workflow with manual launch

on:
  workflow_call:
  workflow_dispatch:
    inputs:
      RG:
        required: true
        type: string
      AKSNAME:
        required: true
        type: string

jobs:
  App_Create:
    runs-on: ubuntu-latest
    steps:
      - name: Job parameter inspection
        run: |
          echo "RG is ${{ inputs.RG }}"
          echo "AKS name is ${{ inputs.AKSNAME }}"
