
name: Resuable workflow with manual launch

on:
  workflow_call:
    inputs:
      RG:
        required: true
        type: string
      AKSNAME:
        required: true
        type: string
  workflow_dispatch:
    inputs:
      RG:
        required: true
        type: string
      AKSNAME:
        required: true
        type: string

jobs:
  Job:
    runs-on: ubuntu-latest
    steps:
      - name: Job parameter inspection
        run: |
          echo "RG is ${{ github.event.inputs.RG }}"
          echo "AKS name is ${{ github.event.inputs.AKSNAME }}"
